version: "3.9"
services:
  mariadb:
    container_name: mariadb-backend
    image: mariadb:10.10.2
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mariadb", "-umariadb", "-pmariadb123"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 2s

  backend:
    container_name: cpp-backend
    build: .
    ports:
      - "19000:19000"
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb-data:
