services:
  code-penal-db:
    container_name: code-penal-db
    image: postgres:17.2-alpine
    ports:
      - "19001:5432"
    volumes:
      - ./legifrance.sql:/docker-entrypoint-initdb.d/legifrance.sql
    environment:
      POSTGRES_USER: legifrance
      POSTGRES_PASSWORD: legifrance123
      POSTGRES_DB: legifrance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legifrance"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-travail-db:
    container_name: code-travail-db
    image: postgres:17.2-alpine
    ports:
      - "19002:5432"
    volumes:
      - ./legifrance.sql:/docker-entrypoint-initdb.d/legifrance.sql
    environment:
      POSTGRES_USER: legifrance
      POSTGRES_PASSWORD: legifrance123
      POSTGRES_DB: legifrance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legifrance"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-actionSociale-db:
    container_name: code-actionSociale-db
    image: postgres:17.2-alpine
    ports:
      - "19003:5432"
    volumes:
      - ./legifrance.sql:/docker-entrypoint-initdb.d/legifrance.sql
    environment:
      POSTGRES_USER: legifrance
      POSTGRES_PASSWORD: legifrance123
      POSTGRES_DB: legifrance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legifrance"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-artisanat-db:
    container_name: code-artisanat-db
    image: postgres:17.2-alpine
    ports:
      - "19004:5432"
    volumes:
      - ./legifrance.sql:/docker-entrypoint-initdb.d/legifrance.sql
    environment:
      POSTGRES_USER: legifrance
      POSTGRES_PASSWORD: legifrance123
      POSTGRES_DB: legifrance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legifrance"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-assurances-db:
    container_name: code-assurances-db
    image: postgres:17.2-alpine
    ports:
      - "19005:5432"
    volumes:
      - ./legifrance.sql:/docker-entrypoint-initdb.d/legifrance.sql
    environment:
      POSTGRES_USER: legifrance
      POSTGRES_PASSWORD: legifrance123
      POSTGRES_DB: legifrance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legifrance"]
      interval: 10s
      timeout: 5s
      retries: 5

  legifrance-manager:
    container_name: legifrance-manager
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      - code-penal-db
      - code-travail-db
      - code-actionSociale-db
    environment:
      ADMINER_DESIGN: dracula

  legifrance-scripts:
    container_name: legifrance-scripts
    build:
      context: ../
      dockerfile: scripts/Dockerfile
    depends_on:
      code-penal-db:
        condition: service_healthy
      code-travail-db:
        condition: service_healthy
    volumes:
      - ./legifrance.sql:/legifrance.sql
    env_file:
      - .env
